// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("Minor Code Smell", "S1075:URIs should not be hardcoded", Justification = "<Pending>", Scope = "member", Target = "~M:WikipediaDeathsPages.Service.ReferenceService.BritannicaUrlFound(System.Collections.Generic.List{System.String},System.String@)~System.Boolean")]
[assembly: SuppressMessage("Minor Code Smell", "S1075:URIs should not be hardcoded", Justification = "<Pending>", Scope = "member", Target = "~M:WikipediaDeathsPages.Service.ReferenceService.BiografischPortaalUrlFound(System.Collections.Generic.List{System.String},System.String@)~System.Boolean")]
[assembly: SuppressMessage("Minor Code Smell", "S1075:URIs should not be hardcoded", Justification = "<Pending>", Scope = "member", Target = "~M:WikipediaDeathsPages.Service.ReferenceService.BnFUrlFound(System.Collections.Generic.List{System.String},System.String@,System.String@)~System.Boolean")]
[assembly: SuppressMessage("Minor Code Smell", "S1075:URIs should not be hardcoded", Justification = "<Pending>", Scope = "member", Target = "~M:WikipediaDeathsPages.Service.ReferenceService.CheckMultiplePlayers(System.String,System.String,System.String,System.DateTime)~System.String")]
[assembly: SuppressMessage("Minor Code Smell", "S1075:URIs should not be hardcoded", Justification = "<Pending>", Scope = "member", Target = "~M:WikipediaDeathsPages.Service.ReferenceService.DbeUrlFound(System.Collections.Generic.List{System.String},System.String@)~System.Boolean")]
[assembly: SuppressMessage("Minor Code Smell", "S1075:URIs should not be hardcoded", Justification = "<Pending>", Scope = "member", Target = "~M:WikipediaDeathsPages.Service.ReferenceService.FemBioUrlFound(System.Collections.Generic.List{System.String},System.String@)~System.Boolean")]
[assembly: SuppressMessage("Minor Code Smell", "S1075:URIs should not be hardcoded", Justification = "<Pending>", Scope = "member", Target = "~M:WikipediaDeathsPages.Service.ReferenceService.FilmportalUrlFound(System.Collections.Generic.List{System.String},System.String@)~System.Boolean")]
[assembly: SuppressMessage("Minor Code Smell", "S1075:URIs should not be hardcoded", Justification = "<Pending>", Scope = "member", Target = "~M:WikipediaDeathsPages.Service.ReferenceService.GetAssociationFootballReference(System.String,System.DateTime)~System.String")]
[assembly: SuppressMessage("Minor Code Smell", "S1075:URIs should not be hardcoded", Justification = "<Pending>", Scope = "member", Target = "~M:WikipediaDeathsPages.Service.ReferenceService.GetCyclistReference(System.String,System.DateTime)~System.String")]
[assembly: SuppressMessage("Minor Code Smell", "S1075:URIs should not be hardcoded", Justification = "<Pending>", Scope = "member", Target = "~M:WikipediaDeathsPages.Service.ReferenceService.GetGolferReference(System.String,System.DateTime)~System.String")]
[assembly: SuppressMessage("Minor Code Smell", "S1075:URIs should not be hardcoded", Justification = "<Pending>", Scope = "member", Target = "~M:WikipediaDeathsPages.Service.ReferenceService.GetOlympediaReference(System.String,System.DateTime)~System.String")]
[assembly: SuppressMessage("Minor Code Smell", "S1075:URIs should not be hardcoded", Justification = "<Pending>", Scope = "member", Target = "~M:WikipediaDeathsPages.Service.ReferenceService.GetSportsReference(System.String,System.String,System.DateTime)~System.String")]
[assembly: SuppressMessage("Minor Code Smell", "S1075:URIs should not be hardcoded", Justification = "<Pending>", Scope = "member", Target = "~M:WikipediaDeathsPages.Service.ReferenceService.IBDBUrlFound(System.Collections.Generic.List{System.String},System.String@)~System.Boolean")]
[assembly: SuppressMessage("Minor Code Smell", "S1075:URIs should not be hardcoded", Justification = "<Pending>", Scope = "member", Target = "~M:WikipediaDeathsPages.Service.ReferenceService.LoCUrlFound(System.Collections.Generic.List{System.String},System.String@)~System.Boolean")]
[assembly: SuppressMessage("Minor Code Smell", "S1075:URIs should not be hardcoded", Justification = "<Pending>", Scope = "member", Target = "~M:WikipediaDeathsPages.Service.ReferenceService.SnacUrlFound(System.Collections.Generic.List{System.String},System.String@)~System.Boolean")]
