// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("Minor Code Smell", "S1075:URIs should not be hardcoded", Justification = "<Pending>", Scope = "member", Target = "~M:WikipediaDeathsPages.Service.ReferenceResolver.BritannicaUrlFound(System.Collections.Generic.List{System.String},System.String@)~System.Boolean")]
[assembly: SuppressMessage("Minor Code Smell", "S1075:URIs should not be hardcoded", Justification = "<Pending>", Scope = "member", Target = "~M:WikipediaDeathsPages.Service.ReferenceResolver.BiografischPortaalUrlFound(System.Collections.Generic.List{System.String},System.String@)~System.Boolean")]
[assembly: SuppressMessage("Minor Code Smell", "S1075:URIs should not be hardcoded", Justification = "<Pending>", Scope = "member", Target = "~M:WikipediaDeathsPages.Service.ReferenceResolver.BnFUrlFound(System.Collections.Generic.List{System.String},System.String@,System.String@)~System.Boolean")]
[assembly: SuppressMessage("Minor Code Smell", "S1075:URIs should not be hardcoded", Justification = "<Pending>", Scope = "member", Target = "~M:WikipediaDeathsPages.Service.ReferenceResolver.CheckMultiplePlayers(System.String,System.String,System.String,System.DateTime)~System.String")]
[assembly: SuppressMessage("Minor Code Smell", "S1075:URIs should not be hardcoded", Justification = "<Pending>", Scope = "member", Target = "~M:WikipediaDeathsPages.Service.ReferenceResolver.DbeUrlFound(System.Collections.Generic.List{System.String},System.String@)~System.Boolean")]
[assembly: SuppressMessage("Minor Code Smell", "S1075:URIs should not be hardcoded", Justification = "<Pending>", Scope = "member", Target = "~M:WikipediaDeathsPages.Service.ReferenceResolver.FemBioUrlFound(System.Collections.Generic.List{System.String},System.String@)~System.Boolean")]
[assembly: SuppressMessage("Minor Code Smell", "S1075:URIs should not be hardcoded", Justification = "<Pending>", Scope = "member", Target = "~M:WikipediaDeathsPages.Service.ReferenceResolver.FilmportalUrlFound(System.Collections.Generic.List{System.String},System.String@)~System.Boolean")]
[assembly: SuppressMessage("Minor Code Smell", "S1075:URIs should not be hardcoded", Justification = "<Pending>", Scope = "member", Target = "~M:WikipediaDeathsPages.Service.ReferenceResolver.GetAssociationFootballReference(System.String,System.DateTime)~System.String")]
[assembly: SuppressMessage("Minor Code Smell", "S1075:URIs should not be hardcoded", Justification = "<Pending>", Scope = "member", Target = "~M:WikipediaDeathsPages.Service.ReferenceResolver.GetCyclistReference(System.String,System.DateTime)~System.String")]
[assembly: SuppressMessage("Minor Code Smell", "S1075:URIs should not be hardcoded", Justification = "<Pending>", Scope = "member", Target = "~M:WikipediaDeathsPages.Service.ReferenceResolver.GetGolferReference(System.String,System.DateTime)~System.String")]
[assembly: SuppressMessage("Minor Code Smell", "S1075:URIs should not be hardcoded", Justification = "<Pending>", Scope = "member", Target = "~M:WikipediaDeathsPages.Service.ReferenceResolver.GetOlympediaReference(System.String,System.DateTime)~System.String")]
[assembly: SuppressMessage("Minor Code Smell", "S1075:URIs should not be hardcoded", Justification = "<Pending>", Scope = "member", Target = "~M:WikipediaDeathsPages.Service.ReferenceResolver.GetSportsReference(System.String,System.String,System.DateTime)~System.String")]
[assembly: SuppressMessage("Minor Code Smell", "S1075:URIs should not be hardcoded", Justification = "<Pending>", Scope = "member", Target = "~M:WikipediaDeathsPages.Service.ReferenceResolver.IBDBUrlFound(System.Collections.Generic.List{System.String},System.String@)~System.Boolean")]
[assembly: SuppressMessage("Minor Code Smell", "S1075:URIs should not be hardcoded", Justification = "<Pending>", Scope = "member", Target = "~M:WikipediaDeathsPages.Service.ReferenceResolver.LoCUrlFound(System.Collections.Generic.List{System.String},System.String@)~System.Boolean")]
[assembly: SuppressMessage("Minor Code Smell", "S1075:URIs should not be hardcoded", Justification = "<Pending>", Scope = "member", Target = "~M:WikipediaDeathsPages.Service.ReferenceResolver.SnacUrlFound(System.Collections.Generic.List{System.String},System.String@)~System.Boolean")]
